### ISSUE TITLE
base/01_use_man.html: 第85-86行

### ISSUE THREAD

**Issue by custa** [me115/linuxtools_rst#3]
以下句子不明白表达的意思，请作者确认是否描述有误
base/01_use_man.html:85-86
对于某个单词搜索，可直接使用/word来使用: /-a; 多关注下SEE ALSO 可看到更多精彩内容

**Comment by me115** [comment]
查询某个命令的参数时使用，
比如查询grep 的-a参数含义
man grep
输入/-a到达相应页面；

当时写的时候含糊了~~
