### ISSUE TITLE
博客地址不维护了？

### ISSUE THREAD

**Issue by callmepeanut** [me115/linuxtools_rst#40]
http://blog.me115.com 这个地址好像变成广告站了，是否下掉？

**Comment by JeffZhu777** [comment]
还报告有木马 
![image](https://user-images.githubusercontent.com/46044340/59091765-9dcfd100-8942-11e9-9924-841b5301ced8.png)

**Comment by me115** [comment]
blog.me115.com






在 2019-06-07 16:38:23，"JeffZhu777" <notifications@github.com> 写道：


还报告有木马

**Comment by me115** [comment]
blog.me115.com 已经不是我的个人博客了。域名已废弃；
这个教程可到这里查看：
http://linuxtools-rst.readthedocs.org/zh_CN/latest/








在 2019-06-07 16:38:23，"JeffZhu777" <notifications@github.com> 写道：


还报告有木马
