### ISSUE TITLE
坑爹的每小时执行实例11

### ISSUE THREAD

**Issue by Jonnyan404** [me115/linuxtools_rst#42]
**实例11的写法是错误的!!!!!!!!!!**
正确的写法为: 
`*/60 * * * * 命令` 或者 `0 * * * * 命令`

**Comment by me115** [comment]
谢谢指出，已修正；

**Comment by Jonnyan404** [comment]
![image](https://user-images.githubusercontent.com/20352705/70592664-9224d600-1c15-11ea-9c98-37b02bf2c088.png)

**Comment by Jonnyan404** [comment]
这里,并未修正,,,,,这里实际是每分钟执行一次,并不是每小时执行.
就这里掉坑里了
![image](https://user-images.githubusercontent.com/20352705/70592762-d2845400-1c15-11ea-817b-b16992d883bc.png)
